services:
  devconn_maintenance:
    image: smartlockertec/devconn_maintenance:v1.0.0
    container_name: devconn_maintenance
    restart: unless-stopped
    env_file:
      - devconn.env
    environment:
      - DMP_MAINTENANCE_USER=${USER}
    volumes:
      - /etc/shadow:/mnt/shadow:ro
      - /etc/ssh:/mnt/host_ssh:ro
      - ${HOME}/.ssh:/mnt/user_ssh:ro
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
