services:
  devconn_connector:
    image: smartlockertec/devconn_connector:v1.2.0
    container_name: devconn_connector
    env_file:
      - devconn.env
    environment:
      CFG_TELEMETRY_PERIOD: 15
      CFG_CONNECTION_INTERMITTENT: false
      ERL_MAX_PORTS: 1024
    restart: unless-stopped
    network_mode: "host"

  pyzer_api_server:
    image: smartlockertec/pyzer_api_server:v1.4.2
    container_name: pyzer_api_server
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - dorian_local_share:/root/.local/share

  pyzer_entity_manager:
    image: smartlockertec/pyzer_entity_manager:v1.4.2
    container_name: pyzer_entity_manager
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    volumes:
      - /run/udev/control:/run/udev/control
      - dorian_local_share:/root/.local/share

  pyflexen_engine:
    image: smartlockertec/pyflexen_engine:v1.7.2
    container_name: pyflexen_engine
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - dorian_local_share:/root/.local/share

  goxmler_app_residential:
    image: smartlockertec/goxmler_app_residential:v2.4.0
    container_name: goxmler_app_residential
    restart: unless-stopped
    network_mode: "host"
    environment:
      - REMOTE_IP=127.0.0.1
      - DISPLAY=:0
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - dorian_local_share:/root/.local/share
    devices:
      - "/dev/dri:/dev/dri"
    profiles: [residential]

  goxmler_app_item_storage:
    image: smartlockertec/goxmler_app_item_storage:v2.0.3
    container_name: goxmler_app_item_storage
    restart: unless-stopped
    network_mode: "host"
    environment:
      - REMOTE_IP=127.0.0.1
      - DISPLAY=:0
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - dorian_local_share:/root/.local/share
    devices:
      - "/dev/dri:/dev/dri"
    profiles: [item_storage] 

  goxmler_app_storage_locker:
    image: smartlockertec/goxmler_app_storage_locker:v1.0.10
    container_name: goxmler_app_storage_locker
    restart: unless-stopped
    network_mode: "host"
    environment:
      - REMOTE_IP=127.0.0.1
      - DISPLAY=:0
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - dorian_local_share:/root/.local/share
    devices:
      - "/dev/dri:/dev/dri"
    profiles: [storage_locker]

  goxmler_app_clever_kiosk:
    image: smartlockertec/goxmler_app_clever_kiosk:v0.9.2
    container_name: goxmler_app_clever_kiosk
    restart: unless-stopped
    network_mode: "host"
    environment:
      - REMOTE_IP=127.0.0.1
      - DISPLAY=:0
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - dorian_local_share:/root/.local/share
    devices:
      - "/dev/dri:/dev/dri"
    profiles: [clever_kiosk]
  
  goxmler_app_click_and_collect:
    image: smartlockertec/goxmler_app_click_and_collect:v0.3.1
    container_name: goxmler_app_click_and_collect
    restart: unless-stopped
    network_mode: "host"
    environment:
      - REMOTE_IP=127.0.0.1
      - DISPLAY=:0
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - dorian_local_share:/root/.local/share
    devices:
      - "/dev/dri:/dev/dri"
    profiles: [click_and_collect]

  goxmler_app_office_locker:
    image: smartlockertec/goxmler_app_office_locker:v1.0.0-34
    container_name: goxmler_app_office_locker
    restart: unless-stopped
    network_mode: "host"
    environment:
      - REMOTE_IP=127.0.0.1
      - DISPLAY=:0
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - dorian_local_share:/root/.local/share
    devices:
      - "/dev/dri:/dev/dri"
    profiles: [office_locker]

volumes:
  dorian_local_share:
    external: true
    name: "dorian_local_share"
